language: cpp
install:
#  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install libgtest-dev -y
  - sudo apt-get install google-mock -y
  - sudo apt-get install cmake
#  - sudo apt-get install doxygen -y
  - cd /usr/src/gtest/
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T Google_hello_world_project-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usrgmatveev:$BINTRAY_API_KEY "https://api.bintray.com/content/srgmatveev/otus-cpp/Google_hello_world_project/$TRAVIS_BUILD_NUMBER/Google_hello_world_project-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
